---
- hosts: ansible-server
  become: true

  tasks:
  - name: create docker image using war file
    command: docker build -t simple-devops-image:latest .
    args:
      chdir: /opt/k8s-lab

  - name: create tag to image
    command: docker tag simple-devops-image ashok44devops/simple-devops-image

  - name: push image on to dockerhub
    command: docker push ashok44devops/simple-devops-image

  - name: remove docker images form ansible server
    command: docker rmi simple-devops-image:latest ashok44devops/simple-devops-image
    ignore_errors: yes
